---
title: ""
output: html_document
---

#### Hoće li biti vjenčanja u crkvi?

Neće.


#### Mogu li doći na ceremoniju u Gornjogradsku vijećnicu?

Gornjogradska vijećnica ima mali kapacitet (16 osoba) i sva mjesta su rezervirana za najbliže članove obitelji, kumove i nas. 

#### Ako ne mogu biti u Gornjogradskoj vijećnici, mogu li vas dočekati ispred nje?

Naravno.

#### Želim vam darovati poklon. Što da radim s njim?

U Studiu Katran ćemo osigurati posebno mjesto na kojem možeš ostaviti poklon. Poklon možeš ostaviti odmah po dolasku u Katran.

#### Razmišljao sam i odlučio da je najbolje da vam poklonim novac, ali se jako bojim nositi gotovinu, opasna su vremena.

Nama je tvoja sigurnost od izuzetne važnosti stoga nam uvijek možeš prebaciti novac na neki od sljedećih načina (Revolut, KeksPay, Coinbase (kripto), PBZ #withPAY, PayPal, … itd.). Ako su ti za to potrebni kakvi dodatni podaci, javi nam se.

#### Kako se moram odjenuti?

Odjeni ono u čemu se ugodno osjećaš. Rezervna odjeća / obuća je poželjna, pogotovo ako želiš presvući cipele ili zaflekanu košulju. Osigurat ćemo mjesto gdje možeš ostaviti svoju odjeću / obuću.

#### Do kada moram minimalno ostati?

Ostani na partiju dokle god ti je ugodno i zabavno. Prije odlaska nam se svakako javi. 

#### Mogu li potplatiti DJa da mi svira npr. ABBAu? 

Ne. DJ nije korumpiran.

#### Što ako mi se neće svidjeti gdje sjedim?

Svidjet će ti se gdje ćeš i s kime sjediti! Potrudit ćemo se napraviti najbolji mogući raspored, a svakako te potičemo da upoznaš druge ljude, na plesnom podiju, u lounge dijelu ili na šanku.
