---
title: ""

output: html_document
---

Za finu hranu angažiran je Catering Muring i trebalo bi biti izvrsno!

Večera će biti poslužena na švedskom stolu, a meni donosimo u nastavku:
 
**Predjelo**

- Dalmatinski pršut, razni naresci (slavonski kulen, laks kare,…)
- Izbor domaćih sireva
- Domaća kuhana šunka pečena u kruhu
- Savici od dimljenog lososa s limunom, maslacem i kaparama
- Riblja pašteta od tune i inćuna
- Carpaccio od povrća
 
**Salad Bar**

- Salata od hobotnice
- Francuska salata
- Meksička salata
- Orijentalna salata s piletinom
- Salata od kozica i artičoka
- Mozzarella i rajčica sa svježim bosiljkom
 
**Sushi corner**

- Tuna nigiri, uromaki, hosomaki
- Losos nigiri, uromaki, hosomaki
- Mango+vege uromaki, hosomaki
- Avokado+vege uromaki, hosomaki
- Philadelphia roll
 
**Topla jela**

- Zapečeni zagorski štrukli
- Wok s povrćem i piletinom
- Istarski fuži u umaku od tartufa
- Mlada Teletina ispod peke s krumpirom
- Pureći jastučići punjeni šunkom i sirom u umaku od šampinjona s valjušcima
- Dalmatinska pašticada s njokima
- Mali zagrebački – povrće na maslacu
- File orade u umaku od bijelog vina s blitvom
 
**Ostalo**

- Buketi miješanih salata
- Domaći kruh s maslinama, sjemenkama i vlascem
- Slatki stol
