---
title: ""
output: html_document
---

**Hoće li biti vjenčanja u crkvi?**

Neće.

**Mogu li doći na ceremoniju u Gornjogradsku vijećnicu?**

Gradska vijećnica ima kapacitet za 16 osoba. 10 mjesta je “rezervirano” za roditelje, kumove i nas. Što znači da je na raspolaganju još 6 mjesta. …. 

**Ako ne mogu biti u Gornjogradskoj vijećnici, mogu li vas dočekati ispred nje i bacati na vas rižu i chia sjemenke?**

Naravno.

**Želim vam darovati poklon. Što da tamo radim s njim?**

Osigurat ćemo posebno mjesto na kojem možeš ostaviti poklon. Poklon možeš ostaviti najkasnije do XX sati.

**Razmišljao sam i odlučio da je najbolje da vam poklonim novac, ali se jako bojim nositi gotovinu, opasna su vremena.**

Nama je tvoja sigurnost od izuzetne važnosti stoga nam uvijek možeš prebaciti novac na neki od sljedećih načina (Revolut, KeksPay, Coinbase (kriptovaluta Leitcoin), PBZ #withPAY, PayPal, … itd.)

**Kako se moram odjenuti?**

Odjeni ono u čemu se ugodno osjećaš. Rezervna odjeća / obuća je poželjna, pogotovo ako želiš presvući cipele ili zaflekanu košulju. Osigurano ćemo mjesto gdje možeš ostaviti svoju odjeću / obuću.

**Do kada moram minimalno ostati?**

Ostani na partiju dokle god ti je ugodno i zabavno. Prije odlaska nam se svakako javi. 

**Mogu li potplatiti DJa da mi svira npr. Kasandru? **

Ne. DJ nije korumpiran.

**Što ako mi se neće svidjet gdje sjedim?**

Svidjet će ti se gdje ćeš i s kime sjediti! Potrudit ćemo se napraviti najbolji mogući raspored, a svakako te potičemo da upoznaš druge ljude, na plesnom podiju,u lounge dijelu ili na šanku.

**Smijem li i ja reći par riječi pred svima?**

Dapače. Potičemo goste da u djelu “Govora” ispričaju koju crticu iz života i našale se na naš račun. Pred svima. No ipak ostavljamo si mogućnost da ti otmemo mikrofon iz ruke i prije kraja. 
